# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import security_pb2 as security__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x05p2p2p\x1a\x0esecurity.proto\"\xca\x01\n\rSignedMessage\x12\x41\n\x11\x65ncrypted_message\x18\x01 \x01(\x0e\x32&.p2p2p.SignedMessage.Encrypted_Message\x12\x16\n\x0esigned_payload\x18\x02 \x01(\x0c\x12\x15\n\rrsa_signature\x18\x03 \x01(\x0c\"G\n\x11\x45ncrypted_Message\x12\x1d\n\x19\x45NCRYPTED_WRAPPED_MESSAGE\x10\x00\x12\x13\n\x0fWRAPPED_MESSAGE\x10\x01\"@\n\x10\x45ncryptedMessage\x12\x19\n\x11\x65ncrypted_payload\x18\x01 \x01(\x0c\x12\x11\n\taes_nonce\x18\x02 \x01(\x0c\"\xe6\x02\n\x0eWrappedMessage\x12+\n\x0cintroduction\x18\x01 \x01(\x0b\x32\x13.p2p2p.IntroductionH\x00\x12\x33\n\x11\x66ile_list_request\x18\x02 \x01(\x0b\x32\x16.p2p2p.FileListRequestH\x00\x12$\n\tfile_list\x18\x03 \x01(\x0b\x32\x0f.p2p2p.FileListH\x00\x12;\n\x15\x66ile_download_request\x18\x04 \x01(\x0b\x32\x1a.p2p2p.FileDownloadRequestH\x00\x12,\n\rfile_download\x18\x05 \x01(\x0b\x32\x13.p2p2p.FileDownloadH\x00\x12\x37\n\x13\x66ile_upload_request\x18\x06 \x01(\x0b\x32\x18.p2p2p.FileUploadRequestH\x00\x12\x1d\n\x05\x65rror\x18\x07 \x01(\x0b\x32\x0c.p2p2p.ErrorH\x00\x42\t\n\x07payload\"g\n\x0cIntroduction\x12+\n\x0ersa_public_key\x18\x01 \x01(\x0b\x32\x13.p2p2p.RsaPublicKey\x12*\n\rdiffe_hellman\x18\x02 \x01(\x0b\x32\x13.p2p2p.DiffeHellman\"\x11\n\x0f\x46ileListRequest\".\n\x08\x46ileList\x12\"\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x13.p2p2p.FileMetadata\"(\n\x13\x46ileDownloadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"4\n\x0c\x46ileDownload\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"9\n\x11\x46ileUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x0c\x46ileMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x42\x1aZ\x18go/types/message;messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030go/types/message;message'
  _globals['_SIGNEDMESSAGE']._serialized_start=41
  _globals['_SIGNEDMESSAGE']._serialized_end=243
  _globals['_SIGNEDMESSAGE_ENCRYPTED_MESSAGE']._serialized_start=172
  _globals['_SIGNEDMESSAGE_ENCRYPTED_MESSAGE']._serialized_end=243
  _globals['_ENCRYPTEDMESSAGE']._serialized_start=245
  _globals['_ENCRYPTEDMESSAGE']._serialized_end=309
  _globals['_WRAPPEDMESSAGE']._serialized_start=312
  _globals['_WRAPPEDMESSAGE']._serialized_end=670
  _globals['_INTRODUCTION']._serialized_start=672
  _globals['_INTRODUCTION']._serialized_end=775
  _globals['_FILELISTREQUEST']._serialized_start=777
  _globals['_FILELISTREQUEST']._serialized_end=794
  _globals['_FILELIST']._serialized_start=796
  _globals['_FILELIST']._serialized_end=842
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=844
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=884
  _globals['_FILEDOWNLOAD']._serialized_start=886
  _globals['_FILEDOWNLOAD']._serialized_end=938
  _globals['_FILEUPLOADREQUEST']._serialized_start=940
  _globals['_FILEUPLOADREQUEST']._serialized_end=997
  _globals['_ERROR']._serialized_start=999
  _globals['_ERROR']._serialized_end=1023
  _globals['_FILEMETADATA']._serialized_start=1025
  _globals['_FILEMETADATA']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
