# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: security.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esecurity.proto\x12\x05p2p2p\"$\n\x0cRsaPublicKey\x12\t\n\x01n\x18\x01 \x01(\x0c\x12\t\n\x01\x65\x18\x02 \x01(\r\"%\n\x0c\x44iffeHellman\x12\x15\n\rdh_public_key\x18\x01 \x01(\x0c\x42\x1cZ\x1ago/types/security;securityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032go/types/security;security'
  _globals['_RSAPUBLICKEY']._serialized_start=25
  _globals['_RSAPUBLICKEY']._serialized_end=61
  _globals['_DIFFEHELLMAN']._serialized_start=63
  _globals['_DIFFEHELLMAN']._serialized_end=100
# @@protoc_insertion_point(module_scope)
